### ISSUE TITLE
Fix(Puestos): Solucionar el id en editar y eliminar

### ISSUE THREAD

**Issue by KarlaRomero17** [KarlaRomero17/sistema_recursos_humanos#15]
Al editar y eliminar, siempre modifica el ultimo registro. Deberá limpiar el textField

**Comment by FerRB27** [comment]
> Al editar y eliminar, siempre modifica el último registro. Deberá limpiar el textField

De acuerdo, le tendré las actualizaciones a la brevedad posible.

**Comment by KarlaRomero17** [comment]
Sigue sin funcionar

**Comment by FerRB27** [comment]
ya deje de reabrirlo ombé
