### ISSUE TITLE
Fix(Puestos): En editar, mostrar la opcion selecionada

### ISSUE THREAD

**Issue by KarlaRomero17** [KarlaRomero17/sistema_recursos_humanos#17]
En el modulo de puestos validar:

- [x] Cargar Id dependencia en la tabla
- [x] Reflejar dinamicamente el depto al que pertenece al seleccionar desde la tabla.
- [x] Cambiar el "Created By" (mostrar nombre en lugar del Id).
- [x] Revisar ortografia

**Comment by FerRB27** [comment]
Subire cambios a mi rama, Considero que pude hacer las correcciones/observacionnes.

Ademas agregue la visualizacion del nombre de la dependencia en la tabla en lugar de el Id de dependencia ya que vi que era factible al modificar el codigo.
El el modelo dejo comentado la logica de como lo use.

**Comment by KarlaRomero17** [comment]
- [ ]  Cambiar # por ID en la tabla de Dependencias

**Comment by KarlaRomero17** [comment]
Revisado, gracias
